definitions: {}
info:
  description: powered by Flasgger
  termsOfService: /tos
  title: A swagger API
  version: 0.0.1
paths:
  /contacts:
    post:
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            name:
              description: "\u0418\u043C\u044F \u043A\u043E\u043D\u0442\u0430\u043A\
                \u0442\u0430"
              example: "\u0421\u0438\u0434\u0440 \u0421\u0438\u0434\u043E\u0440\u043E\
                \u0432"
              type: string
            phone:
              description: "\u041D\u043E\u043C\u0435\u0440 \u0442\u0435\u043B\u0435\
                \u0444\u043E\u043D\u0430"
              example: '+79123456789'
              type: string
          required:
          - name
          - phone
          type: object
      responses:
        '201':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0441\u043E\u0437\
            \u0434\u0430\u043D"
          schema:
            properties:
              id:
                type: integer
              name:
                type: string
              phone:
                type: string
            type: object
        '400':
          description: "\u041D\u0435\u043A\u043E\u0440\u0440\u0435\u043A\u0442\u043D\
            \u044B\u0435 \u0434\u0430\u043D\u043D\u044B\u0435 \u0438\u043B\u0438 \u0438\
            \u043D\u0430\u044F \u043E\u0448\u0438\u0431\u043A\u0430"
          schema:
            properties:
              error:
                type: string
            type: object
      summary: "\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u043D\u043E\u0432\
        \u043E\u0433\u043E \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
      tags:
      - "\u041A\u043E\u043D\u0442\u0430\u043A\u0442\u044B"
  /contacts/{contact_id}:
    delete:
      parameters:
      - description: "ID \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
        in: path
        name: contact_id
        required: true
        type: integer
      responses:
        '200':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0443\u0434\u0430\
            \u043B\u0435\u043D"
          schema:
            properties:
              contact:
                type: object
              message:
                type: string
            type: object
        '404':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435 \u043D\
            \u0430\u0439\u0434\u0435\u043D"
          schema:
            properties:
              error:
                type: string
            type: object
      summary: "\u0423\u0434\u0430\u043B\u0435\u043D\u0438\u0435 \u043A\u043E\u043D\
        \u0442\u0430\u043A\u0442\u0430"
      tags:
      - "\u041A\u043E\u043D\u0442\u0430\u043A\u0442\u044B"
    get:
      parameters:
      - description: "ID \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
        in: path
        name: contact_id
        required: true
        type: integer
      responses:
        '200':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0430\u0439\
            \u0434\u0435\u043D"
          schema:
            properties:
              id:
                type: integer
              name:
                type: string
              phone:
                type: string
            type: object
        '404':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435 \u043D\
            \u0430\u0439\u0434\u0435\u043D"
          schema:
            properties:
              error:
                type: string
            type: object
      summary: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0438\u043D\
        \u0444\u043E\u0440\u043C\u0430\u0446\u0438\u0438 \u043E \u043A\u043E\u043D\
        \u0442\u0430\u043A\u0442\u0435"
      tags:
      - "\u041A\u043E\u043D\u0442\u0430\u043A\u0442\u044B"
swagger: '2.0'
