components:
  schemas: {}
info:
  description: "API \u0434\u043B\u044F \u0443\u043F\u0440\u0430\u0432\u043B\u0435\u043D\
    \u0438\u044F \u0442\u0435\u043B\u0435\u0444\u043E\u043D\u043D\u044B\u043C\u0438\
    \ \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430\u043C\u0438"
  termsOfService: /tos
  title: "\u0422\u0435\u043B\u0435\u0444\u043E\u043D\u043D\u0430\u044F \u043A\u043D\
    \u0438\u0433\u0430 API"
  version: 1.0.0
openapi: 3.0.0
paths:
  /contacts:
    post:
      description: "\u042D\u0442\u043E\u0442 \u044D\u043D\u0434\u043F\u043E\u0438\u043D\
        \u0442 \u043F\u043E\u0437\u0432\u043E\u043B\u044F\u0435\u0442 \u0441\u043E\
        \u0437\u0434\u0430\u0442\u044C \u043D\u043E\u0432\u044B\u0439 \u043A\u043E\
        \u043D\u0442\u0430\u043A\u0442.\n\u0422\u0440\u0435\u0431\u0443\u044E\u0442\
        \u0441\u044F \u043E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u044B\
        \u0435 \u043F\u043E\u043B\u044F name \u0438 phone.\n"
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  description: "\u0418\u043C\u044F \u043A\u043E\u043D\u0442\u0430\u043A\
                    \u0442\u0430"
                  example: "\u0421\u0438\u0434\u0440 \u0421\u0438\u0434\u043E\u0440\
                    \u043E\u0432"
                  type: string
                phone:
                  description: "\u041D\u043E\u043C\u0435\u0440 \u0442\u0435\u043B\u0435\
                    \u0444\u043E\u043D\u0430"
                  example: '+79123456789'
                  type: string
              required:
              - name
              - phone
              type: object
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                properties:
                  id:
                    description: "\u0423\u043D\u0438\u043A\u0430\u043B\u044C\u043D\
                      \u044B\u0439 \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\
                      \u043A\u0430\u0442\u043E\u0440 \u043A\u043E\u043D\u0442\u0430\
                      \u043A\u0442\u0430"
                    example: 5
                    type: integer
                  name:
                    example: "\u0421\u0438\u0434\u0440 \u0421\u0438\u0434\u043E\u0440\
                      \u043E\u0432"
                    type: string
                  phone:
                    example: '+79123456789'
                    type: string
                type: object
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0441\u043E\u0437\
            \u0434\u0430\u043D"
        '400':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: "\u0422\u0440\u0435\u0431\u0443\u044E\u0442\u0441\u044F\
                      \ \u043F\u043E\u043B\u044F name \u0438 phone"
                    type: string
                type: object
          description: "\u041E\u0448\u0438\u0431\u043A\u0430 \u0432 \u0434\u0430\u043D\
            \u043D\u044B\u0445 \u0437\u0430\u043F\u0440\u043E\u0441\u0430"
      summary: "\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u043D\u043E\u0432\
        \u043E\u0433\u043E \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
      tags:
      - "\u041A\u043E\u043D\u0442\u0430\u043A\u0442\u044B"
  /contacts/{contact_id}:
    delete:
      description: "\u0423\u0434\u0430\u043B\u044F\u0435\u0442 \u043A\u043E\u043D\u0442\
        \u0430\u043A\u0442 \u0438\u0437 \u0442\u0435\u043B\u0435\u0444\u043E\u043D\
        \u043D\u043E\u0439 \u043A\u043D\u0438\u0433\u0438 \u043F\u043E \u0435\u0433\
        \u043E \u0443\u043D\u0438\u043A\u0430\u043B\u044C\u043D\u043E\u043C\u0443\
        \ \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0442\u043E\
        \u0440\u0443."
      parameters:
      - description: "\u0423\u043D\u0438\u043A\u0430\u043B\u044C\u043D\u044B\u0439\
          \ \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0442\u043E\
          \u0440 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
        example: 4
        in: path
        name: contact_id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  contact:
                    properties:
                      id:
                        example: 4
                        type: integer
                      name:
                        example: "\u0418\u0432\u0430\u043D \u0418\u0432\u0430\u043D\
                          \u043E\u0432"
                        type: string
                      phone:
                        example: '+79132457680'
                        type: string
                    type: object
                  message:
                    example: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0443\u0434\
                      \u0430\u043B\u0435\u043D"
                    type: string
                type: object
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0443\u0441\u043F\
            \u0435\u0448\u043D\u043E \u0443\u0434\u0430\u043B\u0435\u043D"
        '404':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435\
                      \ \u043D\u0430\u0439\u0434\u0435\u043D"
                    type: string
                type: object
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435 \u043D\
            \u0430\u0439\u0434\u0435\u043D"
      summary: "\u0423\u0434\u0430\u043B\u0435\u043D\u0438\u0435 \u043A\u043E\u043D\
        \u0442\u0430\u043A\u0442\u0430"
      tags:
      - "\u041A\u043E\u043D\u0442\u0430\u043A\u0442\u044B"
    get:
      description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u043F\
        \u043E\u043B\u043D\u0443\u044E \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\
        \u0438\u044E \u043E \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0435 \u043F\
        \u043E \u0435\u0433\u043E \u0443\u043D\u0438\u043A\u0430\u043B\u044C\u043D\
        \u043E\u043C\u0443 \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\
        \u0442\u043E\u0440\u0443."
      parameters:
      - description: "\u0423\u043D\u0438\u043A\u0430\u043B\u044C\u043D\u044B\u0439\
          \ \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0442\u043E\
          \u0440 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
        example: 3
        in: path
        name: contact_id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    example: 3
                    type: integer
                  name:
                    example: "\u041F\u0435\u0442\u0440 \u041F\u0435\u0442\u0440\u043E\
                      \u0432"
                    type: string
                  phone:
                    example: '+79987654321'
                    type: string
                type: object
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0430\u0439\
            \u0434\u0435\u043D"
        '404':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435\
                      \ \u043D\u0430\u0439\u0434\u0435\u043D"
                    type: string
                type: object
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435 \u043D\
            \u0430\u0439\u0434\u0435\u043D"
      summary: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0438\u043D\
        \u0444\u043E\u0440\u043C\u0430\u0446\u0438\u0438 \u043E \u043A\u043E\u043D\
        \u0442\u0430\u043A\u0442\u0435"
      tags:
      - "\u041A\u043E\u043D\u0442\u0430\u043A\u0442\u044B"
